/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as MoreRouteImport } from './routes/more'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StoryRouteImport } from './routes/story'
import { Route as LyricsTrackRouteImport } from './routes/lyrics.$track'
import { Route as TimeTrackRouteImport } from './routes/time.$track'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const LyricsTrackRoute = LyricsTrackRouteImport.update({
  id: '/lyrics/$track',
  path: '/lyrics/$track',
  getParentRoute: () => rootRouteImport,
} as any)
const TimeTrackRoute = TimeTrackRouteImport.update({
  id: '/time/$track',
  path: '/time/$track',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/more': typeof MoreRoute
  '/settings': typeof SettingsRoute
  '/story': typeof StoryRoute
  '/lyrics/$track': typeof LyricsTrackRoute
  '/time/$track': typeof TimeTrackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/more': typeof MoreRoute
  '/settings': typeof SettingsRoute
  '/story': typeof StoryRoute
  '/lyrics/$track': typeof LyricsTrackRoute
  '/time/$track': typeof TimeTrackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/more': typeof MoreRoute
  '/settings': typeof SettingsRoute
  '/story': typeof StoryRoute
  '/lyrics/$track': typeof LyricsTrackRoute
  '/time/$track': typeof TimeTrackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compare'
    | '/more'
    | '/settings'
    | '/story'
    | '/lyrics/$track'
    | '/time/$track'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare'
    | '/more'
    | '/settings'
    | '/story'
    | '/lyrics/$track'
    | '/time/$track'
  id:
    | '__root__'
    | '/'
    | '/compare'
    | '/more'
    | '/settings'
    | '/story'
    | '/lyrics/$track'
    | '/time/$track'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareRoute: typeof CompareRoute
  MoreRoute: typeof MoreRoute
  SettingsRoute: typeof SettingsRoute
  StoryRoute: typeof StoryRoute
  LyricsTrackRoute: typeof LyricsTrackRoute
  TimeTrackRoute: typeof TimeTrackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lyrics/$track': {
      id: '/lyrics/$track'
      path: '/lyrics/$track'
      fullPath: '/lyrics/$track'
      preLoaderRoute: typeof LyricsTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/time/$track': {
      id: '/time/$track'
      path: '/time/$track'
      fullPath: '/time/$track'
      preLoaderRoute: typeof TimeTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareRoute: CompareRoute,
  MoreRoute: MoreRoute,
  SettingsRoute: SettingsRoute,
  StoryRoute: StoryRoute,
  LyricsTrackRoute: LyricsTrackRoute,
  TimeTrackRoute: TimeTrackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
