/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlayerRouteImport } from './routes/_player'
import { Route as PlayerIndexRouteImport } from './routes/_player/index'
import { Route as PlayerLyricsTrackRouteImport } from './routes/_player/lyrics.$track'

const PlayerRoute = PlayerRouteImport.update({
  id: '/_player',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerIndexRoute = PlayerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlayerRoute,
} as any)
const PlayerLyricsTrackRoute = PlayerLyricsTrackRouteImport.update({
  id: '/lyrics/$track',
  path: '/lyrics/$track',
  getParentRoute: () => PlayerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PlayerIndexRoute
  '/lyrics/$track': typeof PlayerLyricsTrackRoute
}
export interface FileRoutesByTo {
  '/': typeof PlayerIndexRoute
  '/lyrics/$track': typeof PlayerLyricsTrackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_player': typeof PlayerRouteWithChildren
  '/_player/': typeof PlayerIndexRoute
  '/_player/lyrics/$track': typeof PlayerLyricsTrackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/lyrics/$track'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/lyrics/$track'
  id: '__root__' | '/_player' | '/_player/' | '/_player/lyrics/$track'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PlayerRoute: typeof PlayerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_player': {
      id: '/_player'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_player/': {
      id: '/_player/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PlayerIndexRouteImport
      parentRoute: typeof PlayerRoute
    }
    '/_player/lyrics/$track': {
      id: '/_player/lyrics/$track'
      path: '/lyrics/$track'
      fullPath: '/lyrics/$track'
      preLoaderRoute: typeof PlayerLyricsTrackRouteImport
      parentRoute: typeof PlayerRoute
    }
  }
}

interface PlayerRouteChildren {
  PlayerIndexRoute: typeof PlayerIndexRoute
  PlayerLyricsTrackRoute: typeof PlayerLyricsTrackRoute
}

const PlayerRouteChildren: PlayerRouteChildren = {
  PlayerIndexRoute: PlayerIndexRoute,
  PlayerLyricsTrackRoute: PlayerLyricsTrackRoute,
}

const PlayerRouteWithChildren =
  PlayerRoute._addFileChildren(PlayerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PlayerRoute: PlayerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
