import { z } from 'zod'
import { lyricsFor } from './lyrics'
import timingData from './timing.json'

export const trackIdSchema = z.enum([
  'pencil',
  'fire',
  'water',
  'memories',
  'baritone',
  'dust',
  'change',
  'hearts',
  'mercy',
  'raven',
  'espoir',
  'beautiful',
  'waves',
])
export type TrackId = z.infer<typeof trackIdSchema>

/** Sing-along timing: start seconds per stanza and per line (see lib/read-along). */
const timingSchema = z.object({
  stanzas: z.array(z.number().nonnegative()),
  lines: z.array(z.array(z.number().nonnegative())),
})

const trackSchema = z.object({
  id: trackIdSchema,
  title: z.string(),
  /** Short dedication for the album card. */
  dedication: z.string(),
  /** The day it was written, ISO YYYY-MM-DD; the timeline and the lyrics header read it. */
  written: z.string().regex(/^\d{4}-\d{2}-\d{2}$/),
  voice: z.string(),
  description: z.string(),
  audioFile: z.string(),
  /** Fallback length in seconds until the element reports metadata. */
  duration: z.number().positive(),
  art: z.object({ full: z.string(), thumb: z.string() }),
  /** Browser chrome color while this track is showing. */
  themeColor: z.string(),
  driveLink: z.url().optional(),
  /**
   * Stanzas of lines from src/data/lyrics/<id>.json. A line wrapped in
   * [brackets] is a label (a section or a voice) and renders small, not sung.
   */
  lyrics: z.array(z.array(z.string()).min(1)),
  /** Whether the words came from a sheet or were transcribed from the recording. */
  lyricsSource: z.enum(['sheet', 'transcribed']),
  /** Generated by the align script from Whisper word timestamps; absent means read by scroll. */
  timing: timingSchema.optional(),
})
export type Track = z.infer<typeof trackSchema>

// timing.json is regenerated by the align script; songs it lacks read by scroll.
const timingFor = (id: TrackId) => (timingData as Record<string, unknown>)[id]

export const TRACK_ORDER: readonly TrackId[] = [
  'pencil',
  'fire',
  'water',
  'memories',
  'baritone',
  'dust',
  'change',
  'hearts',
  'mercy',
  'raven',
  'espoir',
  'beautiful',
  'waves',
]

export const ALBUM = {
  title: 'Fire & Water',
  artist: 'Dustin & Alex',
  tagline: '“You can’t tame the flame.”',
} as const

/** The pair the side-by-side view opens with. */
export const SPLIT_PAIR = { left: 'fire', right: 'water' } as const satisfies {
  left: TrackId
  right: TrackId
}

/** Songs that answer each other: the natural other half of a comparison. */
const PARTNERS: Partial<Record<TrackId, TrackId>> = {
  fire: 'water',
  water: 'fire',
  pencil: 'baritone',
  baritone: 'pencil',
  waves: 'espoir',
  espoir: 'waves',
}

export function comparePartner(id: TrackId): TrackId {
  return (
    PARTNERS[id] ??
    (id === SPLIT_PAIR.left ? SPLIT_PAIR.right : SPLIT_PAIR.left)
  )
}

export const TRACKS: Record<TrackId, Track> = {
  pencil: trackSchema.parse({
    id: 'pencil',
    title: 'Pencil and Pen',
    dedication: 'For Alex, from Dustin',
    written: '2026-03-02',
    voice: 'Dustin’s voice',
    description:
      'A boy who only trusted pencil—erasable, safe, fixable—watches his sister fill journals in permanent ink. Her anger, sadness, and grief poured out fearlessly while he suppressed everything, prayed at night, and bought their lies.',
    audioFile: 'pencil-and-pen.m4a',
    duration: 190,
    art: { full: 'assets/pencil.jpg', thumb: 'assets/pencil-512.jpg' },
    themeColor: '#161009',
    driveLink:
      'https://drive.google.com/file/d/1alDGqv4GfkOC7aRniQswafWXkRDxqAkS/view?usp=drivesdk',
    timing: timingFor('pencil'),
    ...lyricsFor('pencil'),
  }),
  fire: trackSchema.parse({
    id: 'fire',
    title: 'Fire and Water',
    dedication: 'From Dustin, to Alex',
    written: '2026-03-08',
    voice: 'Dustin’s voice',
    description:
      'She was fire—bold, roaring, untamed. He was water—patient, adaptive, persistent. She gave him the courage to speak. He showed her that temperance isn’t weakness. Their parents’ guilt was never hers to carry.',
    audioFile: 'fire-and-water.m4a',
    duration: 400,
    art: { full: 'assets/fire.jpg', thumb: 'assets/fire-512.jpg' },
    themeColor: '#170c06',
    driveLink:
      'https://drive.google.com/file/d/1xaNe-xR3muX_Ptnk9gaGRnwNnCzhpg1T/view?usp=drivesdk',
    timing: timingFor('fire'),
    ...lyricsFor('fire'),
  }),
  water: trackSchema.parse({
    id: 'water',
    title: 'Water and Fire',
    dedication: 'By Dustin, as Alex',
    written: '2026-03-08',
    voice: 'Alex’s voice',
    description:
      'The same story through her eyes. Her fire was never theirs to tame. She channels what used to explode into raising her girls, building a home, and letting go of weight that was never hers to hold.',
    audioFile: 'water-and-fire.m4a',
    duration: 295,
    art: { full: 'assets/water.jpg', thumb: 'assets/water-512.jpg' },
    themeColor: '#0a0e1a',
    driveLink:
      'https://drive.google.com/file/d/1YYdTRD2NAwVekt9VPjAajvD8GQyl727Y/view?usp=drivesdk',
    timing: timingFor('water'),
    ...lyricsFor('water'),
  }),
  memories: trackSchema.parse({
    id: 'memories',
    title: 'Moments to Memories',
    dedication: 'For Alex, from Dustin',
    written: '2026-09-28',
    voice: 'Dustin’s voice, then Dustin Mode',
    description:
      'Pencil lines became journals became code. A brother builds a way to keep what time would steal, so his words outlast him. Then what he built speaks to Alex in his voice.',
    audioFile: 'moments-to-memories.mp3',
    duration: 358,
    art: { full: 'assets/memories.jpg', thumb: 'assets/memories-512.jpg' },
    themeColor: '#120e1c',
    timing: timingFor('memories'),
    ...lyricsFor('memories'),
  }),
  baritone: trackSchema.parse({
    id: 'baritone',
    title: 'Pencil and Pen (Baritone Version)',
    dedication: 'For Alex, from Dustin',
    written: '2026-09-28',
    voice: 'Baritone',
    description:
      'Pencil and Pen, sung low and rewritten around a chorus: the ink in every line, the sketch afraid to shine, and the lock she broke on his mental cage.',
    audioFile: 'pencil-and-pen-baritone.mp3',
    duration: 299,
    art: { full: 'assets/baritone.jpg', thumb: 'assets/baritone-512.jpg' },
    themeColor: '#0f1014',
    timing: timingFor('baritone'),
    ...lyricsFor('baritone'),
  }),
  dust: trackSchema.parse({
    id: 'dust',
    title: 'Dust I Become',
    dedication: 'By Dustin',
    written: '2026-09-28',
    voice: 'Dustin’s voice',
    description:
      'Turned into nothing by someone who always had to be right, he stops begging to be treated the same. Ashes to ashes, dust to dust: he leaves, and becomes his own.',
    audioFile: 'dust-i-become.mp3',
    duration: 285,
    art: { full: 'assets/dust.jpg', thumb: 'assets/dust-512.jpg' },
    themeColor: '#141210',
    timing: timingFor('dust'),
    ...lyricsFor('dust'),
  }),
  change: trackSchema.parse({
    id: 'change',
    title: 'Not Afraid to Change (Extended Hope)',
    dedication: 'By Dustin',
    written: '2026-09-28',
    voice: 'Baritone & soprano',
    description:
      'A baritone and a soprano trade verses through sleepless nights, red-eyed anxiety and the fear of relapse, and refuse to sabotage themselves. Hope, extended.',
    audioFile: 'not-afraid-to-change.mp3',
    duration: 392,
    art: { full: 'assets/change.jpg', thumb: 'assets/change-512.jpg' },
    themeColor: '#0c1512',
    timing: timingFor('change'),
    ...lyricsFor('change'),
  }),
  hearts: trackSchema.parse({
    id: 'hearts',
    title: 'Opposite Hearts',
    dedication: 'By Dustin',
    written: '2026-09-28',
    voice: 'Dustin’s voice',
    description:
      'Born four days past the longest light and four days before the coldest hour: he bends with change, she burns with pride. He teaches water, she teaches fire. Opposite hearts, one rising tide.',
    audioFile: 'opposite-hearts.mp3',
    duration: 342,
    art: { full: 'assets/hearts.jpg', thumb: 'assets/hearts-512.jpg' },
    themeColor: '#1a0c10',
    timing: timingFor('hearts'),
    ...lyricsFor('hearts'),
  }),
  mercy: trackSchema.parse({
    id: 'mercy',
    title: 'Mercy I Owe Myself',
    dedication: 'By Dustin',
    written: '2026-09-29',
    voice: 'Dustin’s voice',
    description:
      'When conflict comes he looks in first: replays every word, searches himself for the cracks, gives everyone else the benefit of the doubt. Relentless self-reflection, and the one mercy he never gives. Maybe the truth is not a trial.',
    audioFile: 'mercy-i-owe-myself.mp3',
    duration: 247,
    art: { full: 'assets/mercy.jpg', thumb: 'assets/mercy-512.jpg' },
    themeColor: '#17120d',
    timing: timingFor('mercy'),
    ...lyricsFor('mercy'),
  }),
  raven: trackSchema.parse({
    id: 'raven',
    title: 'Magic of the Raven',
    dedication: 'By Dustin',
    written: '2026-09-29',
    voice: 'Dustin’s voice',
    description:
      'Nothing to fear, dear child: the shadow returns and the raven is here. A magician stands where light meets darkness, wingbeats of creation carry prayers through the midnight air, and childhood pain asks to be released, with an Irish chant to the black raven: fiach dubh, iompair mé.',
    audioFile: 'magic-of-the-raven.mp3',
    duration: 332,
    art: { full: 'assets/raven.jpg', thumb: 'assets/raven-512.jpg' },
    themeColor: '#0a0d1e',
    timing: timingFor('raven'),
    ...lyricsFor('raven'),
  }),
  espoir: trackSchema.parse({
    id: 'espoir',
    title: 'L’espoir est à moi (en français)',
    dedication: 'By Dustin, in French',
    written: '2026-09-29',
    voice: 'En français',
    description:
      'Waves of Hope, sung in French: l’espoir n’est pas aveugle, l’espoir est à moi. A choice made each morning and each night, over rough roads and black nights.',
    audioFile: 'lespoir-est-a-moi.mp3',
    duration: 320,
    art: { full: 'assets/espoir.jpg', thumb: 'assets/espoir-512.jpg' },
    themeColor: '#070c1a',
    timing: timingFor('espoir'),
    ...lyricsFor('espoir'),
  }),
  beautiful: trackSchema.parse({
    id: 'beautiful',
    title: 'I Make It Beautiful',
    dedication: 'By Dustin',
    written: '2026-09-29',
    voice: 'Dustin’s voice',
    description:
      'Earth held the fear, water the guilt, air the grief, fire the shame, and the songs came before the knowing. Seventeen of them speak as one: wound, rewrite, redirect. He takes the dark and makes it beautiful.',
    audioFile: 'i-make-it-beautiful.mp3',
    duration: 240,
    art: { full: 'assets/beautiful.jpg', thumb: 'assets/beautiful-512.jpg' },
    themeColor: '#100c08',
    timing: timingFor('beautiful'),
    ...lyricsFor('beautiful'),
  }),
  waves: trackSchema.parse({
    id: 'waves',
    title: 'Waves of Hope',
    dedication: 'By Dustin',
    written: '2026-09-29',
    voice: 'Dustin’s voice',
    description:
      'Hope is not blind, hope is mine: a choice made every morning and every night, through setback, friction and the fight, until every bruise becomes a map for where to go.',
    audioFile: 'waves-of-hope.mp3',
    duration: 317,
    art: { full: 'assets/waves.jpg', thumb: 'assets/waves-512.jpg' },
    themeColor: '#0e0d0a',
    timing: timingFor('waves'),
    ...lyricsFor('waves'),
  }),
}

export function adjacentTrack(id: TrackId, direction: 1 | -1): TrackId {
  const i = TRACK_ORDER.indexOf(id)
  return TRACK_ORDER[(i + direction + TRACK_ORDER.length) % TRACK_ORDER.length]
}

export function isLastTrack(id: TrackId) {
  return TRACK_ORDER.indexOf(id) === TRACK_ORDER.length - 1
}

/** A line wrapped in [brackets] is a section or voice label, not sung. */
export function isLyricLabel(line: string) {
  return line.startsWith('[') && line.endsWith(']')
}

type Lyrics = ReadonlyArray<ReadonlyArray<string>>

/** True when two sheets line up stanza for stanza and line for line, like the mirrored pair. */
export function sameLyricShape(a: Lyrics, b: Lyrics) {
  return a.length === b.length && a.every((s, i) => s.length === b[i].length)
}

/** "March 2, 2026": the day it was written, spelled out. */
export function writtenDate(t: Track) {
  return new Date(`${t.written}T12:00:00`).toLocaleDateString('en-US', {
    month: 'long',
    day: 'numeric',
    year: 'numeric',
  })
}

/** "For Alex, from Dustin — March 2, 2026": the dedication with the date, for the action sheet. */
export function dedicationLine(t: Track) {
  return `${t.dedication} — ${writtenDate(t)}`
}

/** "Fire & Water", "Not Afraid to Change": the title without its parenthetical, for tight spots. */
export function shortTitle(id: TrackId) {
  return TRACKS[id].title.replace(' and ', ' & ').replace(/\s*\(.*\)$/, '')
}
