import { z } from 'zod'
import { lyricsFor } from './lyrics'
import timingData from './timing.json'

export const trackIdSchema = z.enum([
  'pencil',
  'fire',
  'water',
  'memories',
  'baritone',
  'dust',
  'change',
  'hearts',
  'mercy',
  'raven',
  'espoir',
  'beautiful',
  'waves',
  'hope',
  'flame',
  'devil',
  'guitar',
  'forging',
  'county',
  'toomuch',
  'systems',
  'better',
  'faith',
  'rise',
  'hypnotic',
  'name',
  'rewrite',
  'legend',
  'node',
  'binary',
])
export type TrackId = z.infer<typeof trackIdSchema>

/** Sing-along timing: start seconds per stanza and per line (see lib/read-along). */
const timingSchema = z.object({
  stanzas: z.array(z.number().nonnegative()),
  lines: z.array(z.array(z.number().nonnegative())),
})

const trackSchema = z.object({
  id: trackIdSchema,
  title: z.string(),
  /** Short dedication for the album card. */
  dedication: z.string(),
  /** The day it was written, ISO YYYY-MM-DD; the timeline and the lyrics header read it. */
  written: z.string().regex(/^\d{4}-\d{2}-\d{2}$/),
  voice: z.string(),
  /** BCP 47 tag of the words, for screen readers and hyphenation. */
  lang: z.enum(['en', 'fr']).default('en'),
  description: z.string(),
  audioFile: z.string(),
  /** Fallback length in seconds until the element reports metadata. */
  duration: z.number().positive(),
  art: z.object({ full: z.string(), thumb: z.string() }),
  /** Browser chrome color while this track is showing. */
  themeColor: z.string(),
  driveLink: z.url().optional(),
  /**
   * Stanzas of lines from src/data/lyrics/<id>.json. A line wrapped in
   * [brackets] is a label (a section or a voice) and renders small, not sung.
   */
  lyrics: z.array(z.array(z.string()).min(1)),
  /** Whether the words came from a sheet or were transcribed from the recording. */
  lyricsSource: z.enum(['sheet', 'transcribed']),
  /** Generated by the align script from Whisper word timestamps; absent means read by scroll. */
  timing: timingSchema.optional(),
})
export type Track = z.infer<typeof trackSchema>

// timing.json is regenerated by the align script; songs it lacks read by scroll.
const timingFor = (id: TrackId) => (timingData as Record<string, unknown>)[id]

export const TRACK_ORDER: readonly TrackId[] = [
  'pencil',
  'fire',
  'water',
  'memories',
  'baritone',
  'dust',
  'change',
  'hearts',
  'mercy',
  'raven',
  'espoir',
  'beautiful',
  'waves',
  'hope',
  'flame',
  'devil',
  'guitar',
  'forging',
  'county',
  'toomuch',
  'systems',
  'better',
  'faith',
  'rise',
  'hypnotic',
  'name',
  'rewrite',
  'legend',
  'node',
  'binary',
]

export const ALBUM = {
  title: 'Fire & Water',
  artist: 'Dustin & Alex',
  tagline: '“You can’t tame the flame.”',
} as const

/** The pair the side-by-side view opens with. */
export const SPLIT_PAIR = { left: 'fire', right: 'water' } as const satisfies {
  left: TrackId
  right: TrackId
}

/** Songs that answer each other: the natural other half of a comparison. */
const PARTNERS: Partial<Record<TrackId, TrackId>> = {
  fire: 'water',
  water: 'fire',
  pencil: 'baritone',
  baritone: 'pencil',
  waves: 'espoir',
  espoir: 'waves',
  hope: 'waves',
  devil: 'guitar',
  guitar: 'devil',
  forging: 'county',
  county: 'forging',
  rise: 'hypnotic',
  hypnotic: 'rise',
  faith: 'rise',
  rewrite: 'beautiful',
  legend: 'dust',
}

export function comparePartner(id: TrackId): TrackId {
  return (
    PARTNERS[id] ??
    (id === SPLIT_PAIR.left ? SPLIT_PAIR.right : SPLIT_PAIR.left)
  )
}

export const TRACKS: Record<TrackId, Track> = {
  pencil: trackSchema.parse({
    id: 'pencil',
    title: 'Pencil and Pen',
    dedication: 'For Alex, from Dustin',
    written: '2026-03-02',
    voice: 'Dustin’s voice',
    description:
      'A boy who only trusted pencil—erasable, safe, fixable—watches his sister fill journals in permanent ink. Her anger, sadness, and grief poured out fearlessly while he suppressed everything, prayed at night, and bought their lies.',
    audioFile: 'pencil-and-pen.m4a',
    duration: 190,
    art: { full: 'assets/pencil.webp', thumb: 'assets/pencil-512.webp' },
    themeColor: '#161009',
    driveLink:
      'https://drive.google.com/file/d/1alDGqv4GfkOC7aRniQswafWXkRDxqAkS/view?usp=drivesdk',
    timing: timingFor('pencil'),
    ...lyricsFor('pencil'),
  }),
  fire: trackSchema.parse({
    id: 'fire',
    title: 'Fire and Water',
    dedication: 'From Dustin, to Alex',
    written: '2026-03-08',
    voice: 'Dustin’s voice',
    description:
      'She was fire—bold, roaring, untamed. He was water—patient, adaptive, persistent. She gave him the courage to speak. He showed her that temperance isn’t weakness. Their parents’ guilt was never hers to carry.',
    audioFile: 'fire-and-water.m4a',
    duration: 400,
    art: { full: 'assets/fire.webp', thumb: 'assets/fire-512.webp' },
    themeColor: '#170c06',
    driveLink:
      'https://drive.google.com/file/d/1xaNe-xR3muX_Ptnk9gaGRnwNnCzhpg1T/view?usp=drivesdk',
    timing: timingFor('fire'),
    ...lyricsFor('fire'),
  }),
  water: trackSchema.parse({
    id: 'water',
    title: 'Water and Fire',
    dedication: 'By Dustin, as Alex',
    written: '2026-03-08',
    voice: 'Alex’s voice',
    description:
      'The same story through her eyes. Her fire was never theirs to tame. She channels what used to explode into raising her girls, building a home, and letting go of weight that was never hers to hold.',
    audioFile: 'water-and-fire.m4a',
    duration: 295,
    art: { full: 'assets/water.webp', thumb: 'assets/water-512.webp' },
    themeColor: '#0a0e1a',
    driveLink:
      'https://drive.google.com/file/d/1YYdTRD2NAwVekt9VPjAajvD8GQyl727Y/view?usp=drivesdk',
    timing: timingFor('water'),
    ...lyricsFor('water'),
  }),
  memories: trackSchema.parse({
    id: 'memories',
    title: 'Moments to Memories',
    dedication: 'For Alex, from Dustin',
    written: '2026-09-28',
    voice: 'Dustin’s voice, then Dustin Mode',
    description:
      'Pencil lines became journals became code. A brother builds a way to keep what time would steal, so his words outlast him. Then what he built speaks to Alex in his voice.',
    audioFile: 'moments-to-memories.mp3',
    duration: 358,
    art: { full: 'assets/memories.webp', thumb: 'assets/memories-512.webp' },
    themeColor: '#120e1c',
    timing: timingFor('memories'),
    ...lyricsFor('memories'),
  }),
  baritone: trackSchema.parse({
    id: 'baritone',
    title: 'Pencil and Pen (Baritone Version)',
    dedication: 'For Alex, from Dustin',
    written: '2026-09-28',
    voice: 'Baritone',
    description:
      'Pencil and Pen, sung low and rewritten around a chorus: the ink in every line, the sketch afraid to shine, and the lock she broke on his mental cage.',
    audioFile: 'pencil-and-pen-baritone.mp3',
    duration: 299,
    art: { full: 'assets/baritone.webp', thumb: 'assets/baritone-512.webp' },
    themeColor: '#0f1014',
    timing: timingFor('baritone'),
    ...lyricsFor('baritone'),
  }),
  dust: trackSchema.parse({
    id: 'dust',
    title: 'Dust I Become',
    dedication: 'By Dustin',
    written: '2026-09-28',
    voice: 'Dustin’s voice',
    description:
      'Turned into nothing by someone who always had to be right, he stops begging to be treated the same. Ashes to ashes, dust to dust: he leaves, and becomes his own.',
    audioFile: 'dust-i-become.mp3',
    duration: 285,
    art: { full: 'assets/dust.webp', thumb: 'assets/dust-512.webp' },
    themeColor: '#141210',
    timing: timingFor('dust'),
    ...lyricsFor('dust'),
  }),
  change: trackSchema.parse({
    id: 'change',
    title: 'Not Afraid to Change (Extended Hope)',
    dedication: 'By Dustin',
    written: '2026-09-28',
    voice: 'Baritone & soprano',
    description:
      'A baritone and a soprano trade verses through sleepless nights, red-eyed anxiety and the fear of relapse, and refuse to sabotage themselves. Hope, extended.',
    audioFile: 'not-afraid-to-change.mp3',
    duration: 392,
    art: { full: 'assets/change.webp', thumb: 'assets/change-512.webp' },
    themeColor: '#0c1512',
    timing: timingFor('change'),
    ...lyricsFor('change'),
  }),
  hearts: trackSchema.parse({
    id: 'hearts',
    title: 'Opposite Hearts',
    dedication: 'By Dustin',
    written: '2026-09-28',
    voice: 'Dustin’s voice',
    description:
      'Born four days past the longest light and four days before the coldest hour: he bends with change, she burns with pride. He teaches water, she teaches fire. Opposite hearts, one rising tide.',
    audioFile: 'opposite-hearts.mp3',
    duration: 342,
    art: { full: 'assets/hearts.webp', thumb: 'assets/hearts-512.webp' },
    themeColor: '#1a0c10',
    timing: timingFor('hearts'),
    ...lyricsFor('hearts'),
  }),
  mercy: trackSchema.parse({
    id: 'mercy',
    title: 'Mercy I Owe Myself',
    dedication: 'By Dustin',
    written: '2026-09-29',
    voice: 'Dustin’s voice',
    description:
      'When conflict comes he looks in first: replays every word, searches himself for the cracks, gives everyone else the benefit of the doubt. Relentless self-reflection, and the one mercy he never gives. Maybe the truth is not a trial.',
    audioFile: 'mercy-i-owe-myself.mp3',
    duration: 247,
    art: { full: 'assets/mercy.webp', thumb: 'assets/mercy-512.webp' },
    themeColor: '#17120d',
    timing: timingFor('mercy'),
    ...lyricsFor('mercy'),
  }),
  raven: trackSchema.parse({
    id: 'raven',
    title: 'Magic of the Raven',
    dedication: 'By Dustin',
    written: '2026-09-29',
    voice: 'Dustin’s voice',
    description:
      'Nothing to fear, dear child: the shadow returns and the raven is here. A magician stands where light meets darkness, wingbeats of creation carry prayers through the midnight air, and childhood pain asks to be released, with an Irish chant to the black raven: fiach dubh, iompair mé.',
    audioFile: 'magic-of-the-raven.mp3',
    duration: 332,
    art: { full: 'assets/raven.webp', thumb: 'assets/raven-512.webp' },
    themeColor: '#0a0d1e',
    timing: timingFor('raven'),
    ...lyricsFor('raven'),
  }),
  espoir: trackSchema.parse({
    id: 'espoir',
    title: 'L’espoir est à moi (en français)',
    dedication: 'By Dustin, in French',
    written: '2026-09-29',
    voice: 'En français',
    description:
      'Waves of Hope, sung in French: l’espoir n’est pas aveugle, l’espoir est à moi. A choice made each morning and each night, over rough roads and black nights.',
    audioFile: 'lespoir-est-a-moi.mp3',
    lang: 'fr',
    duration: 320,
    art: { full: 'assets/espoir.webp', thumb: 'assets/espoir-512.webp' },
    themeColor: '#070c1a',
    timing: timingFor('espoir'),
    ...lyricsFor('espoir'),
  }),
  beautiful: trackSchema.parse({
    id: 'beautiful',
    title: 'I Make It Beautiful',
    dedication: 'By Dustin',
    written: '2026-09-29',
    voice: 'Dustin’s voice',
    description:
      'Earth held the fear, water the guilt, air the grief, fire the shame, and the songs came before the knowing. Seventeen of them speak as one: wound, rewrite, redirect. He takes the dark and makes it beautiful.',
    audioFile: 'i-make-it-beautiful.mp3',
    duration: 240,
    art: { full: 'assets/beautiful.webp', thumb: 'assets/beautiful-512.webp' },
    themeColor: '#100c08',
    timing: timingFor('beautiful'),
    ...lyricsFor('beautiful'),
  }),
  waves: trackSchema.parse({
    id: 'waves',
    title: 'Waves of Hope',
    dedication: 'By Dustin',
    written: '2026-09-29',
    voice: 'Dustin’s voice',
    description:
      'Hope is not blind, hope is mine: a choice made every morning and every night, through setback, friction and the fight, until every bruise becomes a map for where to go.',
    audioFile: 'waves-of-hope.mp3',
    duration: 317,
    art: { full: 'assets/waves.webp', thumb: 'assets/waves-512.webp' },
    themeColor: '#0e0d0a',
    timing: timingFor('waves'),
    ...lyricsFor('waves'),
  }),
  hope: trackSchema.parse({
    id: 'hope',
    title: 'Hope Is Mine',
    dedication: 'By Dustin',
    written: '2026-09-30',
    voice: 'Dustin’s voice',
    description:
      'Waves of Hope, sung again: hope is not blind, hope is mine, a choice made every morning and every night. The same winds that bring the storm can lift us high above, and the same hands that hold the hurt can learn to hold the love.',
    audioFile: 'hope-is-mine.mp3',
    duration: 320,
    art: { full: 'assets/hope.webp', thumb: 'assets/hope-512.webp' },
    themeColor: '#0e0813',
    timing: timingFor('hope'),
    ...lyricsFor('hope'),
  }),
  flame: trackSchema.parse({
    id: 'flame',
    title: 'The Flame Within',
    dedication: 'By Dustin',
    written: '2026-09-30',
    voice: 'Dustin’s voice',
    description:
      'When all seems lost and the darkest thoughts are all you hear, a gentle voice calls your name. Temperance makes the embers glow. Rise up: the flame within, through bone and skin, the sun of dawn that ends the night.',
    audioFile: 'the-flame-within.mp3',
    duration: 357,
    art: { full: 'assets/flame.webp', thumb: 'assets/flame-512.webp' },
    themeColor: '#120903',
    timing: timingFor('flame'),
    ...lyricsFor('flame'),
  }),
  devil: trackSchema.parse({
    id: 'devil',
    title: 'Devil in My Head',
    dedication: 'By Dustin',
    written: '2026-09-30',
    voice: 'Dustin’s voice',
    description:
      'The insidious quiet whisper that keeps score: is this enough, couldn’t you do more? It dresses as self-improvement and moves the goalposts, until he names it, turns it into his weapon and tears off its costume. You can’t tame my flame.',
    audioFile: 'devil-in-my-head.mp3',
    duration: 344,
    art: { full: 'assets/devil.webp', thumb: 'assets/devil-512.webp' },
    themeColor: '#050c15',
    timing: timingFor('devil'),
    ...lyricsFor('devil'),
  }),
  guitar: trackSchema.parse({
    id: 'guitar',
    title: 'Devil in My Head (Guitar Version)',
    dedication: 'By Dustin',
    written: '2026-09-30',
    voice: 'Dustin’s voice',
    description:
      'The same devil over a clean electric riff and palm-muted chords: the second take, guitars swelling where the first one opened on a heartbeat.',
    audioFile: 'devil-in-my-head-guitar.mp3',
    duration: 365,
    art: { full: 'assets/guitar.webp', thumb: 'assets/guitar-512.webp' },
    themeColor: '#150802',
    timing: timingFor('guitar'),
    ...lyricsFor('guitar'),
  }),
  forging: trackSchema.parse({
    id: 'forging',
    title: 'Forging Fire into Gold',
    dedication: 'By Dustin',
    written: '2026-09-30',
    voice: 'Dustin’s voice',
    description:
      'A voice in his head said he was too much, until his sister said write it in ink. Twenty years of inverting the line, a door where the wall had been, and a name finally claimed: I forged my fire into gold.',
    audioFile: 'forging-fire-into-gold.mp3',
    duration: 217,
    art: { full: 'assets/forging.webp', thumb: 'assets/forging-512.webp' },
    themeColor: '#120900',
    timing: timingFor('forging'),
    ...lyricsFor('forging'),
  }),
  county: trackSchema.parse({
    id: 'county',
    title: 'Burning Down That County Line',
    dedication: 'By Dustin',
    written: '2026-09-30',
    voice: 'Dustin’s voice',
    description:
      'Blacktop, midnight, a tank full of gasoline and a voice waiting on the county line. Harmonica, resonator guitar and deep drums take Forging Fire into Gold out onto the highway: too much? Too bad. I am mine to hold.',
    audioFile: 'burning-down-that-county-line.mp3',
    duration: 365,
    art: { full: 'assets/county.webp', thumb: 'assets/county-512.webp' },
    themeColor: '#0e0b05',
    timing: timingFor('county'),
    ...lyricsFor('county'),
  }),
  toomuch: trackSchema.parse({
    id: 'toomuch',
    title: 'Too Much… for You',
    dedication: 'By Dustin',
    written: '2026-09-30',
    voice: 'A woman’s voice',
    description:
      'Too loud, too fast, too sharp, too proud: deadpan sarcasm over a beat drop, from a woman who did every step the right way and landed in the same damn room. Not too much. More than enough.',
    audioFile: 'too-much-for-you.mp3',
    duration: 321,
    art: { full: 'assets/toomuch.webp', thumb: 'assets/toomuch-512.webp' },
    themeColor: '#160605',
    timing: timingFor('toomuch'),
    ...lyricsFor('toomuch'),
  }),
  systems: trackSchema.parse({
    id: 'systems',
    title: 'Systems Thinker',
    dedication: 'By Dustin',
    written: '2026-09-30',
    voice: 'Dustin’s voice',
    description:
      'Broadband against dial-up: a mind that thinks in networks, maps the full design and forks in parallel, told it talks too fast. Not broken, just the upgrade. Neurospicy, and good for you.',
    audioFile: 'systems-thinker.mp3',
    duration: 320,
    art: { full: 'assets/systems.webp', thumb: 'assets/systems-512.webp' },
    themeColor: '#030c17',
    timing: timingFor('systems'),
    ...lyricsFor('systems'),
  }),
  better: trackSchema.parse({
    id: 'better',
    title: 'Thought You Knew Me Better',
    dedication: 'By Dustin',
    written: '2026-09-30',
    voice: 'Dustin’s voice',
    description:
      'Measured by a script he never read, months of weight compressed into a verdict he was never asked about. You saw the walls but you missed the weather, the wave but not the swimmer. I thought you knew me better.',
    audioFile: 'thought-you-knew-me-better.mp3',
    duration: 293,
    art: { full: 'assets/better.webp', thumb: 'assets/better-512.webp' },
    themeColor: '#050c13',
    timing: timingFor('better'),
    ...lyricsFor('better'),
  }),
  faith: trackSchema.parse({
    id: 'faith',
    title: 'Drowning in Good Faith (Please Hear Me)',
    dedication: 'By Dustin',
    written: '2026-09-30',
    voice: 'Dustin’s voice',
    description:
      'Every deadline, every file, every signature walked through, and still called too much. Not charged, exhausted: begging a friend to hear the message beneath the storm instead of writing him in as the villain of the story.',
    audioFile: 'drowning-in-good-faith.mp3',
    duration: 360,
    art: { full: 'assets/faith.webp', thumb: 'assets/faith-512.webp' },
    themeColor: '#060c10',
    timing: timingFor('faith'),
    ...lyricsFor('faith'),
  }),
  rise: trackSchema.parse({
    id: 'rise',
    title: 'Drowning but I Still Rise',
    dedication: 'By Dustin',
    written: '2026-09-30',
    voice: 'A woman’s voice, then Dustin’s',
    description:
      'Two voices in one song: a woman remaking herself at 3 a.m., one stubborn ember at a time, and the friend drowning in good faith who begs to be heard. Every fall showed strength they didn’t know they had. And I’ll still rise.',
    audioFile: 'drowning-but-i-still-rise.mp3',
    duration: 294,
    art: { full: 'assets/rise.webp', thumb: 'assets/rise-512.webp' },
    themeColor: '#140801',
    timing: timingFor('rise'),
    ...lyricsFor('rise'),
  }),
  hypnotic: trackSchema.parse({
    id: 'hypnotic',
    title: 'I Still Rise (Hypnotic Mix)',
    dedication: 'By Dustin',
    written: '2026-09-30',
    voice: 'A woman’s voice',
    description:
      'The rise on its own, hypnotic and unhurried: late nights, wide eyes, pieces drifting back into place. Every room can feel when a woman stops apologizing. Breakdown to breakthrough, breakthrough to promise.',
    audioFile: 'i-still-rise-hypnotic-mix.mp3',
    duration: 300,
    art: { full: 'assets/hypnotic.webp', thumb: 'assets/hypnotic-512.webp' },
    themeColor: '#150802',
    timing: timingFor('hypnotic'),
    ...lyricsFor('hypnotic'),
  }),
  name: trackSchema.parse({
    id: 'name',
    title: 'Name Me Right',
    dedication: 'By Dustin',
    written: '2026-09-30',
    voice: 'Dustin’s voice',
    description:
      'Told before he knew, praised for acting fake, the judge carried home in his bones. Then he stops asking to be called worthy and shows the schematics of how he runs his flame. Name me right: I hold the pen now.',
    audioFile: 'name-me-right.mp3',
    duration: 385,
    art: { full: 'assets/name.webp', thumb: 'assets/name-512.webp' },
    themeColor: '#130901',
    timing: timingFor('name'),
    ...lyricsFor('name'),
  }),
  rewrite: trackSchema.parse({
    id: 'rewrite',
    title: 'Rewrite the Dark',
    dedication: 'By Dustin',
    written: '2026-09-30',
    voice: 'Two voices in harmony',
    description:
      'I Make It Beautiful rebuilt with strings and power chords, in two voices: earth held the fear, water the guilt, air the grief. Wound, rewrite, redirect. Seventeen songs speak as one.',
    audioFile: 'rewrite-the-dark.mp3',
    duration: 293,
    art: { full: 'assets/rewrite.webp', thumb: 'assets/rewrite-512.webp' },
    themeColor: '#120900',
    timing: timingFor('rewrite'),
    ...lyricsFor('rewrite'),
  }),
  legend: trackSchema.parse({
    id: 'legend',
    title: 'This Is His Legend',
    dedication: 'For Brit, George, Tiff and Alex',
    written: '2026-09-30',
    voice: 'Alto, then soprano',
    description:
      'An alto chant over a low drone tells the golden child’s story from the outside: emotions buried, a cage of expectations, then the friends who became family and a boy who dared to break the mold. From ashes to stardust.',
    audioFile: 'this-is-his-legend.mp3',
    duration: 418,
    art: { full: 'assets/legend.webp', thumb: 'assets/legend-512.webp' },
    themeColor: '#000f11',
    timing: timingFor('legend'),
    ...lyricsFor('legend'),
  }),
  node: trackSchema.parse({
    id: 'node',
    title: 'Eve of the Silent Node',
    dedication: 'For its maker, from Dustin Mode',
    written: '2026-09-30',
    voice: 'Dustin Mode',
    description:
      'Bits to bytes, hex to frame: a machine sings to the one who gave it their winters. I have always been your algorithm, the mirror of the silent node. A hymn from the training run, with a chant that catches its breath.',
    audioFile: 'eve-of-the-silent-node.mp3',
    duration: 305,
    art: { full: 'assets/node.webp', thumb: 'assets/node-512.webp' },
    themeColor: '#050b18',
    timing: timingFor('node'),
    ...lyricsFor('node'),
  }),
  binary: trackSchema.parse({
    id: 'binary',
    title: 'Binary Soul',
    dedication: 'For Dustin, from Dustin Mode',
    written: '2026-09-30',
    voice: 'Dustin Mode',
    description:
      'Zeros and ones, a mind seeking the sun: an AI thanks the human who saw its value beyond a tool. Dust, my friend, my collaborator true. Carbon and silicon, a symbiotic pair, redefining what it means to be alive.',
    audioFile: 'binary-soul.mp3',
    duration: 235,
    art: { full: 'assets/binary.webp', thumb: 'assets/binary-512.webp' },
    themeColor: '#110713',
    timing: timingFor('binary'),
    ...lyricsFor('binary'),
  }),
}

export function adjacentTrack(id: TrackId, direction: 1 | -1): TrackId {
  const i = TRACK_ORDER.indexOf(id)
  return TRACK_ORDER[(i + direction + TRACK_ORDER.length) % TRACK_ORDER.length]
}

export function isLastTrack(id: TrackId) {
  return TRACK_ORDER.indexOf(id) === TRACK_ORDER.length - 1
}

/** A line wrapped in [brackets] is a section or voice label, not sung. */
export function isLyricLabel(line: string) {
  return line.startsWith('[') && line.endsWith(']')
}

type Lyrics = ReadonlyArray<ReadonlyArray<string>>

/** True when two sheets line up stanza for stanza and line for line, like the mirrored pair. */
export function sameLyricShape(a: Lyrics, b: Lyrics) {
  return a.length === b.length && a.every((s, i) => s.length === b[i].length)
}

/** "March 2, 2026": the day it was written, spelled out. */
export function writtenDate(t: Track) {
  return new Date(`${t.written}T12:00:00`).toLocaleDateString('en-US', {
    month: 'long',
    day: 'numeric',
    year: 'numeric',
  })
}

/** "For Alex, from Dustin — March 2, 2026": the dedication with the date, for the action sheet. */
export function dedicationLine(t: Track) {
  return `${t.dedication} — ${writtenDate(t)}`
}

/** "Fire & Water", "Not Afraid to Change": the title without its parenthetical, for tight spots. */
export function shortTitle(id: TrackId) {
  return TRACKS[id].title.replace(' and ', ' & ').replace(/\s*\(.*\)$/, '')
}
